// this code was generated by chatGPT AI code generator
using UnityEngine;

public class ArrayManipulator : MonoBehaviour
{
    // the array, you can change the type to any other you want, just be sure to update the function
    public int[] myArray;

    public void AddElementToArray(int element, int index)
    {
        if (index < 0 || index > myArray.Length)
        {
            Debug.LogError("Invalid index. Please enter a value between 0 and " + (myArray.Length - 1));
            return;
        }
        int[] newArray = new int[myArray.Length + 1];
        for (int i = 0; i < myArray.Length; i++)
        {
            if (i < index)
            {
                newArray[i] = myArray[i];
            }
            else
            {
                newArray[i + 1] = myArray[i];
            }
        }
        newArray[index] = element;
        myArray = newArray;
    }

    public void RemoveElementFromArray(int index)
    {
        if (index < 0 || index > myArray.Length - 1)
        {
            Debug.LogError("Invalid index. Please enter a value between 0 and " + (myArray.Length - 1));
            return;
        }
        int[] newArray = new int[myArray.Length - 1];
        for (int i = 0, j = 0; i < myArray.Length; i++)
        {
            if (i != index)
            {
                newArray[j] = myArray[i];
                j++;
            }
        }
        myArray = newArray;
    }
}
