// this code was generated by chatGPT AI code generator
using UnityEngine;

public class CalculateRatio : MonoBehaviour
{
    public float maxVal;
    public float minVal;
    public float theNum;
    public float minFloat = 0;
    public float maxFloat = 1;

    private float ratio;

    void Start()
    {
        ratio = (theNum - minVal) / (maxVal - minVal);
        float finalFloat = Mathf.Lerp(minFloat, maxFloat, ratio);
        Debug.Log("The ratio of " + theNum + " between " + minVal + " and " + maxVal + " is: " + ratio);
        Debug.Log("The mapped float value is: " + finalFloat);
    }
}
