// this code was generated by chatGPT AI code generator
using UnityEngine;

public class CameraWobble : MonoBehaviour
{
    public float intensity = 0.1f;
    public float speed = 1f;

    private Vector3 initialPosition;

    void Start()
    {
        initialPosition = transform.position;
    }

    void Update()
    {
        float x = Mathf.Sin(Time.time * speed) * intensity;
        float y = Mathf.Cos(Time.time * speed) * intensity;
        transform.position = initialPosition + new Vector3(x, y, 0);
    }
}
