// this code was generated by chatGPT AI code generator
using UnityEngine;

public class CheckDotValue : MonoBehaviour
{
    public float dotThresholdHigh = 0.8f;
    public float dotThresholdLow = -0.8f;

    public bool isMovingForward;
    public bool isMovingBackward;

    private Rigidbody rb;

    void Start()
    {
        rb = GetComponent<Rigidbody>();
    }

    void Update()
    {
        float dotValue = Vector3.Dot(rb.velocity.normalized, transform.forward);

        if (dotValue > dotThresholdHigh)
        {
            isMovingForward = true;
        }
        else
        {
            isMovingForward = false;
        }

        if (dotValue < dotThresholdLow)
        {
            isMovingBackward = true;
        }
        else
        {
            isMovingBackward = false;
        }
    }
}
