// this code was generated by chatGPT AI code generator
using UnityEngine;

public class ComponentChecker : MonoBehaviour
{
    public Component component;
    public GameObject gameObject;

    private void Start()
    {
        if (gameObject.GetComponent(component.GetType()) != null)
        {
            Debug.Log(gameObject.name + " has the " + component.GetType().Name + " component");
        }
        else
        {
            Debug.Log(gameObject.name + " does not have the " + component.GetType().Name + " component");
        }
    }
}
