// this code was generated by chatGPT AI code generator
using System.Collections.Generic;
using UnityEngine;

public class inventoryManager : MonoBehaviour
{
    private Dictionary<int, GameObject> objectDict = new Dictionary<int, GameObject>();
    private int lastIndex = 0;

    // Function to add a GameObject to the dictionary
    public void AddObject(GameObject obj)
    {
        objectDict.Add(lastIndex++, obj);
    }

    // Function to get a GameObject from the dictionary based on index
    public GameObject GetObject(int index)
    {
        if (objectDict.ContainsKey(index))
        {
            return objectDict[index];
        }
        else
        {
            Debug.LogWarning("GameObject with index " + index + " does not exist in dictionary.");
            return null;
        }
    }

    // Function to list all GameObjects in a List<GameObject> variable
    public void ListAllObjects(List<GameObject> objectList)
    {
        objectList.Clear();

        foreach (KeyValuePair<int, GameObject> entry in objectDict)
        {
            objectList.Add(entry.Value);
        }
    }

    // Function to check if a GameObject of a certain name is in the dictionary
    public bool ObjectExists(string objName)
    {
        foreach (KeyValuePair<int, GameObject> entry in objectDict)
        {
            if (entry.Value.name == objName)
            {
                return true;
            }
        }

        return false;
    }

    // Function to remove a GameObject from the dictionary based on its name
    public bool RemoveObject(string objName)
    {
        foreach (KeyValuePair<int, GameObject> entry in objectDict)
        {
            if (entry.Value.name == objName)
            {
                objectDict.Remove(entry.Key);
                return true;
            }
        }

        return false;
    }
}
