// this code was generated by chatGPT AI code generator
using UnityEngine;
using System.Collections;

public class OpenLink : MonoBehaviour
{
    public string link;

    public void OpenInBrowser()
    {
        Application.OpenURL(link);
    }
}
