// this code was generated by chatGPT AI code generator
using UnityEngine;

public class PrefabLoader : MonoBehaviour
{
    public string prefabName;

    void Start()
    {
        GameObject prefab = Resources.Load<GameObject>(prefabName);
        Instantiate(prefab);
    }
}
