// this code was generated by chatGPT AI code generator
using UnityEngine;

public class RotateTowards : MonoBehaviour
{
    public Transform destination;
    public Transform moveMe;
    public float delay;

    private float timeElapsed = 0f;
    private Quaternion initialRotation;

    void Start()
    {
        initialRotation = moveMe.rotation;
    }

    void Update()
    {
        timeElapsed += Time.deltaTime;

        if (timeElapsed < delay)
        {
            moveMe.rotation = Quaternion.Slerp(initialRotation, destination.rotation, timeElapsed / delay);
        }
    }
}
