// this code was generated by chatGPT AI code generator
using UnityEngine;
using UnityEngine.UI;

public class barUpdater : MonoBehaviour
{
    public Image refObj;        // Reference Image component
    public Image changeObj;     // Image component to be changed

    public float delay = 1.0f;      // Delay before reducing fill amount
    public float timeFactor = 0.1f; // Rate at which fill amount is reduced

    private float timeElapsed = 0.0f;    // Time elapsed since delay
    private float refFillAmount = 0.0f;  // Fill amount of reference Image component

    void Start()
    {
        // Store initial fill amount of reference Image component
        refFillAmount = refObj.fillAmount;
    }

    void Update()
    {
        // Check if fill amount of changeObj is less than refObj
        if (changeObj.fillAmount < refFillAmount)
        {
            // Wait for delay before reducing fill amount
            if (timeElapsed < delay)
            {
                timeElapsed += Time.deltaTime;
            }
            else
            {
                // Reduce fill amount by timeFactor * time since last frame
                changeObj.fillAmount -= timeFactor * Time.deltaTime;
            }
        }
        else
        {
            // Snap fill amount of changeObj to refObj
            changeObj.fillAmount = refFillAmount;
        }
    }
}
