// this code was generated by chatGPT AI code generator
using UnityEngine;

public class CarController : MonoBehaviour
{
    public WheelCollider frontLeftWheel, frontRightWheel, rearLeftWheel, rearRightWheel;
    public float maxSteerAngle = 30f;
    public float motorForce = 50f;
    public float brakeForce = 100f;
    public float driftFactor = 0.1f;

    private float steer;
    private float accel;
    private float brake;

    void FixedUpdate()
    {
        steer = Input.GetAxis("Horizontal");
        accel = Input.GetAxis("Vertical");
        brake = Input.GetAxis("Jump");

        frontLeftWheel.steerAngle = steer * maxSteerAngle;
        frontRightWheel.steerAngle = steer * maxSteerAngle;

        // Apply drift to the rear wheels
        rearLeftWheel.GetComponent<WheelCollider>().sidewaysFriction = new WheelFrictionCurve();
        rearLeftWheel.GetComponent<WheelCollider>().sidewaysFriction.stiffness = 1f;
        rearRightWheel.GetComponent<WheelCollider>().sidewaysFriction = new WheelFrictionCurve();
        rearRightWheel.GetComponent<WheelCollider>().sidewaysFriction.stiffness = 1f;

        // Add force to the wheels
        rearLeftWheel.motorTorque = accel * motorForce;
        rearRightWheel.motorTorque = accel * motorForce;

        // Apply braking force
        rearLeftWheel.brakeTorque = brake * brakeForce;
        rearRightWheel.brakeTorque = brake * brakeForce;
    }
}
