// this code was generated by chatGPT AI code generator
using UnityEngine;

public class FogController : MonoBehaviour
{
    public float density;
    public Color fogColor;

    private void Update()
    {
        RenderSettings.fog = true;
        RenderSettings.fogDensity = density;
        RenderSettings.fogColor = fogColor;
    }
}