// this code was generated by chatGPT AI code generator
using UnityEngine;

public class GetUsername : MonoBehaviour
{
    void Start()
    {
        string username = System.Environment.UserName;
        Debug.Log("Username: " + username);
    }
}