// this code was generated by chatGPT AI code generator
using UnityEngine;

public class ItemCycler : MonoBehaviour
{
    public GameObject[] items;
    public float interval;
    private int cno;
    private float timeElapsed;

    void Start()
    {
        cno = 0;
        DeactivateAll();
        items[cno].SetActive(true);
    }

    void Update()
    {
        timeElapsed += Time.deltaTime;
        if (timeElapsed >= interval)
        {
            timeElapsed = 0;
            cno++;
            if (cno >= items.Length)
            {
                cno = 0;
            }
            DeactivateAll();
            items[cno].SetActive(true);
        }
    }

    private void DeactivateAll()
    {
        foreach (GameObject item in items)
        {
            item.SetActive(false);
        }
    }
}
