// this code was generated by chatGPT AI code generator
using UnityEngine;

public class KeyboardInput : MonoBehaviour
{
    private string inputString = "";

    private void Update()
    {
        foreach (char c in Input.inputString)
        {
            if (char.IsLetter(c))
            {
                inputString += c;
            }
        }
    }

    public bool checkInside(string what)
    {
        return inputString.Contains(what);
    }

    public void ClearInputString()
    {
        inputString = "";
    }
}
