// this code was generated by chatGPT AI code generator
using UnityEngine;

public class MoveTowards : MonoBehaviour
{
    public Transform destination;
    public Transform moveMe;
    public float delay;

    private float timeElapsed = 0f;
    private Vector3 initialPosition;

    void Start()
    {
        initialPosition = moveMe.position;
    }

    void Update()
    {
        timeElapsed += Time.deltaTime;

        if (timeElapsed < delay)
        {
            moveMe.position = Vector3.Lerp(initialPosition, destination.position, timeElapsed / delay);
        }
    }
}
