// this code was generated by chatGPT AI code generator
using UnityEngine;

public class PerlinNoiseMesh : MonoBehaviour
{
    public int length = 100;
    public int width = 100;
    public int height = 20;
    public float scale = 20f;

    void Start()
    {
        Mesh mesh = new Mesh();
        GetComponent<MeshFilter>().mesh = mesh;

        Vector3[] vertices = new Vector3[length * width];
        int[] triangles = new int[(length - 1) * (width - 1) * 6];
        Vector2[] uv = new Vector2[length * width];

        for (int x = 0; x < length; x++)
        {
            for (int y = 0; y < width; y++)
            {
                float perlinValue = Mathf.PerlinNoise((float)x / scale, (float)y / scale);
                vertices[x + y * length] = new Vector3(x, perlinValue * height, y);
                uv[x + y * length] = new Vector2((float)x / length, (float)y / width);
            }
        }

        int triIndex = 0;
        for (int x = 0; x < length - 1; x++)
        {
            for (int y = 0; y < width - 1; y++)
            {
                triangles[triIndex] = x + y * length;
                triangles[triIndex + 1] = x + (y + 1) * length;
                triangles[triIndex + 2] = (x + 1) + y * length;

                triangles[triIndex + 3] = (x + 1) + y * length;
                triangles[triIndex + 4] = x + (y + 1) * length;
                triangles[triIndex + 5] = (x + 1) + (y + 1) * length;

                triIndex += 6;
            }
        }

        mesh.vertices = vertices;
        mesh.triangles = triangles;
        mesh.uv = uv;
        mesh.RecalculateNormals();
    }
}
