// this code was generated by chatGPT AI code generator
using UnityEngine;
using UnityEditor;

public class PickImage : MonoBehaviour
{
    public string filePath;
    public string resourceFolder = "Resources/";

    void Start()
    {
        filePath = EditorUtility.OpenFilePanel("Select Image", "", "jpg,png,gif");
        if (!string.IsNullOrEmpty(filePath))
        {
            byte[] fileData = File.ReadAllBytes(filePath);
            Texture2D texture = new Texture2D(2, 2);
            texture.LoadImage(fileData);
            string fileName = Path.GetFileName(filePath);
            string resourcePath = resourceFolder + fileName;

            // check if the file already exist
            if (AssetDatabase.LoadAssetAtPath(resourcePath, typeof(Texture2D)))
            {
                AssetDatabase.DeleteAsset(resourcePath);
            }
            // Create new asset
            AssetDatabase.CreateAsset(texture, resourcePath);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }
    }
}
