// this code was generated by chatGPT AI code generator
using UnityEngine;

public class SkyboxRotator : MonoBehaviour
{
    public Vector3 rotationSpeed;

    private void Update()
    {
        RenderSettings.skybox.SetFloat("_Rotation", Time.time * rotationSpeed.z);
    }
}
