// this code was generated by chatGPT AI code generator
using UnityEngine;

public class SpawnParticlesOnCollision : MonoBehaviour
{
    public ParticleSystem particles;
    public bool spawnOnEnter = true;
    public bool spawnOnStay = false;
    public bool spawnOnExit = false;

    private void OnCollisionEnter(Collision collision)
    {
        if (spawnOnEnter)
        {
            SpawnParticles(collision);
        }
    }

    private void OnCollisionStay(Collision collision)
    {
        if (spawnOnStay)
        {
            SpawnParticles(collision);
        }
    }

    private void OnCollisionExit(Collision collision)
    {
        if (spawnOnExit)
        {
            SpawnParticles(collision);
        }
    }

    private void SpawnParticles(Collision collision)
    {
        foreach (ContactPoint contact in collision.contacts)
        {
            ParticleSystem particleClone = Instantiate(particles, contact.point, Quaternion.identity);
            particleClone.Play();
            Destroy(particleClone.gameObject, particleClone.main.duration);
        }
    }
}
