// this code was generated by chatGPT AI code generator
using UnityEngine;
using System;

public class TimeConverter : MonoBehaviour
{
    public float secs;

    public string timeTxt;

    void Start()
    {
      timeTxt = ToHMS(secs);
    }

    public string ToHMS(float what){
      TimeSpan time = TimeSpan.FromSeconds(what);
      string hms = string.Format("{0:D2}h:{1:D2}m:{2:D2}.{3:D3}s",time.Hours,time.Minutes,time.Seconds,time.Milliseconds);
      return hms;
    }

    public string ToMS(float what){
      TimeSpan time = TimeSpan.FromSeconds(what);
      string hms = string.Format("{1:D2}m:{2:D2}.{3:D3}s",time.Minutes,time.Seconds,time.Milliseconds);
      return hms;
    }
}
