// this code was generated by chatGPT AI code generator
using UnityEngine;

public class CameraTransparency : MonoBehaviour
{
    public Shader transparentShader;
    public float maxDistance = 10;
    private Camera cam;

    void Start()
    {
        cam = GetComponent<Camera>();
        cam.SetReplacementShader(transparentShader, "RenderType");
        Shader.SetGlobalFloat("_MaxDistance", maxDistance);
    }
}
