// this code was generated by chatGPT AI code generator
using UnityEngine;

[ExecuteInEditMode]
public class CameraWarp : MonoBehaviour
{
    public Material warpMaterial;
    public float intensity = 0.1f;
    public float speed = 1f;
    private Camera cam;

    private void OnRenderImage(RenderTexture source, RenderTexture destination)
    {
        if (warpMaterial != null)
        {
            warpMaterial.SetFloat("_Intensity", intensity);
            warpMaterial.SetFloat("_Speed", speed);
            Graphics.Blit(source, destination, warpMaterial);
        }
        else
        {
            Graphics.Blit(source, destination);
        }
    }

    private void Start()
    {
        cam = GetComponent<Camera>();
        cam.depthTextureMode = DepthTextureMode.Depth;
    }
}
