// this code was generated by chatGPT AI code generator
using UnityEngine;

public class OutlineCamera : MonoBehaviour
{
    public Color outlineColor = Color.white;
    public Color backgroundColor = Color.black;
    public LayerMask outlineLayers;
    private Camera cam;
    private Material outlineMaterial;

    private void OnEnable()
    {
        cam = GetComponent<Camera>();
        cam.clearFlags = CameraClearFlags.SolidColor;
        cam.backgroundColor = backgroundColor;
        CreateOutlineMaterial();
        cam.cullingMask &= ~(1 << LayerMask.NameToLayer("Outline"));
    }

    private void CreateOutlineMaterial()
    {
        outlineMaterial = new Material(Shader.Find("Custom/Outline"));
        outlineMaterial.SetColor("_OutlineColor", outlineColor);
        outlineMaterial.SetFloat("_Outline", 0.005f);
    }

    private void OnPreRender()
    {
        // Enable the outline effect on specified layers
        for (int i = 0; i < 32; i++)
        {
            if (outlineLayers == (outlineLayers | (1 << i)))
            {
                RenderOutline(i);
            }
        }
    }

    private void RenderOutline(int i)
    {
        var temp = cam.cullingMask;
        cam.cullingMask = 1 << i;
        for (int j = 0; j < cam.pixelWidth; j++)
        {
            for (int k = 0; k < cam.pixelHeight; k++)
            {
                cam.RenderWithShader(outlineMaterial.shader, "");
            }
        }
        cam.cullingMask = temp;
    }

}
