// this code was generated by chatGPT AI code generator
using UnityEngine;

public class CheatsListener : MonoBehaviour
{
    [SerializeField] string inputString = "";
    public string[] cheats;
    public bool activated = false;
    public bool cheatEntered = false;
    public int cheatid = 0;
    public string lastcheat = "none yet";

    private void Update()
    {
        if(Time.timeScale < 0.9 || activated){
            foreach (char c in Input.inputString){
                if (char.IsLetter(c))
                {
                    inputString += c; 
                }
            }

            if(Input.GetKeyDown(KeyCode.Return)){
                cheatHandler();
            }

            if(Input.GetKeyDown(KeyCode.Delete)){
                ClearInputString();
            }
        }

        if(Input.GetKey(KeyCode.LeftShift) || Input.GetKey(KeyCode.RightShift)){
            if(Input.GetKeyDown(KeyCode.C)){
                activated = activated ? false : true;
            }
        }
    }

    public bool checkInside(string what)
    {
        inputString = inputString.ToLower();
        return inputString.Contains(what);
    }

    public void ClearInputString()
    {
        inputString = "";
    }

    void cheatHandler(){
        for (int x = 0; x < cheats.Length; x++){
            cheats[x] = cheats[x].ToLower();

            // Debug.Log("cheatSys : " + checkInside(cheats[x]) + " [inputstring - "+inputString+"] & [cheat is - "+cheats[x]+"]");

            if(checkInside(cheats[x])){
                cheatid = x;
                cheatEntered = true;
                break;
            } else {
                cheatid = -1;
            }
        }

        string ouTxt;
        if(cheatid >= 0){
            ouTxt = "cheat code entered : " + inputString;
            lastcheat = inputString;
        }else{
            ouTxt = "enter a valid cheatcode";
        }

        Debug.Log("cheatSys : " + ouTxt);
        ClearInputString();
    }
}
