// this code was generated by chatGPT AI code generator
using UnityEngine;
using UnityEngine.UI;

public class barUpdater : MonoBehaviour
{
    public Image refObj;        // Reference Image component
    public Image changeObj;     // Image component to be changed

    public float delay = 1.0f;      // Delay before reducing fill amount
    public float timeFactor = 0.1f; // Rate at which fill amount is reduced

    public float timeElapsed = 0.0f;    // Time elapsed since delay
    public float refFillAmount = 0.0f;  // Fill amount of reference Image component

    public bool autocheck = true;
    public bool lessen = true;

    void Start()
    {
        changeObj.fillAmount = lessen ? 1f : 0f;
        updatebar();
    }

    void Update()
    {
        if(lessen){
            if (changeObj.fillAmount > refFillAmount){
                if (timeElapsed < delay){
                    timeElapsed += Time.deltaTime;
                }
                else{
                    changeObj.fillAmount -= timeFactor * Time.deltaTime;
                }
            }else{
                changeObj.fillAmount = refFillAmount;
            }
        } else {
            if (changeObj.fillAmount < refFillAmount){
                if (timeElapsed < delay){
                    timeElapsed += Time.deltaTime;
                }
                else{
                    changeObj.fillAmount += timeFactor * Time.deltaTime;
                }
            }else{
                changeObj.fillAmount = refFillAmount;
            }
        }

        if(autocheck){
            if(refFillAmount != refObj.fillAmount){refFillAmount = refObj.fillAmount;updatebar();}
        }
    }

    public void updatebar(){
        refFillAmount = refObj.fillAmount;
        timeElapsed = 0.0f;
    }
}
