// this code was generated by chatGPT AI code generator
using UnityEngine;
using System.Reflection;
using System.Collections.Generic;

public class PropertyLister : MonoBehaviour
{
    public Component itemType;
    public bool runit;
    public List<string> allProperties = new List<string>();
    
    void Update() {
        if(runit){runit=false;ListProperties(itemType.GetType());}
    }

    public void ListProperties(System.Type type){
        PropertyInfo[] properties = type.GetProperties();

        foreach (PropertyInfo property in properties)
        {
            allProperties.Clear();
            allProperties.Add(property.Name);
        }
    }
}

// Example usage
public class MyClass
{
    public int MyIntProperty { get; set; }
    public string MyStringProperty { get; set; }
}

public class Example : MonoBehaviour
{
    public PropertyLister propertyLister;

    void Start()
    {
        propertyLister.ListProperties(typeof(MyClass));
        foreach(string property in propertyLister.allProperties)
        {
            Debug.Log(property);
        }
    }
}
